env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  {
    'import/extensions': 'off',
    'import/no-unresolved': 'off',
    'no-confusing-arrow': 'off',
    'linebreak-style': 'off',
    'implicit-arrow-linebreak': 'off',
    'function-paren-newline': 'off',
    'comma-dangle': 'off',
    'no-use-before-define': 'off',
    'camelcase': 'off',
    'react/jsx-filename-extension': 'off',
    'react/react-in-jsx-scope': 'off',
    'no-shadow': 'off',
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    'indent': 'off',
    'react/prop-types': 'off',
    'react/require-default-props': 'off',
    'dot-notation': 'off',
  }
