version: '3.6'
services:
  postgres:
    image: postgres:12
    container_name: Postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      POSTGRES_PASSWORD: a
  PgAdmin:
    image: dpage/pgadmin4
    container_name: PgAdmin
    restart: 'no'
    ports:
      - '82:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.fr
      PGADMIN_DEFAULT_PASSWORD: a
  graphql-engine:
    image: hasura/graphql-engine:latest
    container_name: Hasura
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:a@postgres:5432/postgres
      PG_DATABASE_URL: postgres://postgres:a@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false'
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_LIVE_QUERIES_MULTIPLEXED_REFETCH_INTERVAL: 50
      HASURA_GRAPHQL_JWT_SECRET: '{  "type": "HS256",  "key":
        "f1c9bceb42f92ffc8648e04a70f2f50b91ac9f2f5b74994e5c00f7cf0f0326b1b98c574a2ebaaaa8f62e6b8d03116560bd81c8ae396b2e0fb5342e78a1208748",
        "claims_namespace_path": "$$.claims"}'
      HASURA_GRAPHQL_ADMIN_SECRET: flo
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
volumes:
  db_data: null
